// Run: node worker/seed.mjs
// The Worker API must be running on localhost:8787

const API = 'http://localhost:8787/api';

const questions = [
  // ── PART 1: Data, Variables & Sampling ──
  { part:1, text:'The PhilHealth database contains records of all 11.4 million members in the National Capital Region. A researcher randomly selects 3,000 of these members and records their monthly premium contributions. The ₱1,250 average computed from those 3,000 records is best described as a:',
    choices:[{key:'A',text:'Parameter, because it describes a population characteristic'},{key:'B',text:'Statistic, because it is computed from a sample'},{key:'C',text:'Variable, because premium amounts differ per member'},{key:'D',text:'Population, because PhilHealth covers all Filipinos'}], answer:'B',
    explain:'A statistic is computed from a sample. The 3,000 members are the sample; ₱1,250 is the statistic.' },
  { part:1, text:'A DepEd study records the <em>exact body weight in kilograms</em> of Grade 7 students in a public school for a nutrition monitoring program. What type of variable is body weight?',
    choices:[{key:'A',text:'Qualitative'},{key:'B',text:'Quantitative-Discrete'},{key:'C',text:'Quantitative-Continuous'},{key:'D',text:'Categorical-Ordinal'}], answer:'C',
    explain:'Body weight is measured on a continuous scale and can take decimal values (e.g., 42.7 kg).' },
  { part:1, text:'An LTO researcher records the <em>type of vehicle</em> registered by each motorist (Motorcycle, Sedan, SUV, Truck, Van). This variable is:',
    choices:[{key:'A',text:'Quantitative-Continuous'},{key:'B',text:'Quantitative-Discrete'},{key:'C',text:'Qualitative (Categorical)'},{key:'D',text:'Continuous ratio-level'}], answer:'C',
    explain:'Vehicle type is a label/category — it cannot be ordered or averaged, making it qualitative.' },
  { part:1, text:'A barangay health center records the <em>number of dengue cases</em> reported per week. This variable is:',
    choices:[{key:'A',text:'Qualitative, because it refers to disease type'},{key:'B',text:'Quantitative-Continuous, because it can take decimal values'},{key:'C',text:'Quantitative-Discrete, because cases are whole-number counts'},{key:'D',text:'Categorical-Nominal, because health data is always categorical'}], answer:'C',
    explain:'Dengue cases are counted in whole numbers (you cannot have 2.5 cases), so the variable is discrete.' },
  { part:1, text:'A COMELEC analyst surveys 500 registered voters in Davao City to estimate the proportion who support a ballot measure. In this study, the <em>population</em> is:',
    choices:[{key:'A',text:'The 500 voters who were surveyed'},{key:'B',text:'All registered voters in Davao City'},{key:'C',text:'All registered voters in the Philippines'},{key:'D',text:'The COMELEC analyst conducting the survey'}], answer:'B',
    explain:'The population is the entire group of interest — all registered voters in Davao City.' },
  { part:1, text:'Which of the following is an example of a <em>parameter</em>?',
    choices:[{key:'A',text:'The average monthly electricity bill of 200 randomly chosen Meralco customers'},{key:'B',text:'The true mean daily ridership of all MRT-3 passengers in 2024'},{key:'C',text:'The proportion of heads in 100 coin tosses'},{key:'D',text:'The standard deviation of test scores from a sample of 60 students'}], answer:'B',
    explain:'A parameter describes the entire population. The true mean ridership of ALL MRT-3 passengers is a parameter.' },
  { part:1, text:'A researcher assigns each employee an ID from 1 to 800, then uses a random number generator to select 80 employees. This method is called:',
    choices:[{key:'A',text:'Stratified random sampling'},{key:'B',text:'Cluster sampling'},{key:'C',text:'Simple random sampling'},{key:'D',text:'Convenience sampling'}], answer:'C',
    explain:'Simple random sampling gives every member an equal chance of selection using a random mechanism.' },
  { part:1, text:'A national survey divides the Philippines into Luzon, Visayas, and Mindanao, then randomly samples respondents <em>within each group</em>. This best describes:',
    choices:[{key:'A',text:'Simple random sampling'},{key:'B',text:'Systematic sampling'},{key:'C',text:'Stratified random sampling'},{key:'D',text:'Cluster sampling'}], answer:'C',
    explain:'Dividing into strata (groups) and sampling within each group is stratified random sampling.' },
  { part:1, text:'A school nurse surveys only the students who happen to be in the clinic on a Monday morning. This sampling method is most likely to produce:',
    choices:[{key:'A',text:'A representative, unbiased sample'},{key:'B',text:'A sample with no sampling error'},{key:'C',text:'A biased sample due to convenience sampling'},{key:'D',text:'A stratified sample of sick students'}], answer:'C',
    explain:'Surveying only whoever is conveniently available (clinic patients) is convenience sampling, which introduces bias.' },
  { part:1, text:'The PSA conducts the census and counts every Filipino household. The resulting average household size of 4.1 persons is a:',
    choices:[{key:'A',text:'Statistic, because it was computed by the PSA'},{key:'B',text:'Parameter, because it describes the entire population'},{key:'C',text:'Sample mean, because it is an average'},{key:'D',text:'Variable, because household size varies'}], answer:'B',
    explain:'Because the census covers every household (the full population), the resulting figure is a parameter.' },

  // ── PART 2: Central Tendency ──
  { part:2, text:'Seven tricycle drivers in Batangas recorded their daily earnings (in pesos):{{DATA:380,420,455,490,510,530,960}}What is the mean daily earnings?',
    choices:[{key:'A',text:'₱490.00'},{key:'B',text:'₱535.00'},{key:'C',text:'₱535.71'},{key:'D',text:'₱492.14'}], answer:'C',
    explain:'Sum = 380+420+455+490+510+530+960 = 3,745. Mean = 3,745 ÷ 7 ≈ ₱535.71.' },
  { part:2, text:'Using the same tricycle driver data:{{DATA:380,420,455,490,510,530,960}}What is the <em>median</em> daily earnings?',
    choices:[{key:'A',text:'₱455'},{key:'B',text:'₱490'},{key:'C',text:'₱510'},{key:'D',text:'₱500'}], answer:'B',
    explain:'Sorted: 380,420,455,490,510,530,960. The 4th value (middle of 7) = ₱490.' },
  { part:2, text:'Because one driver earned ₱960 (far above the rest), a journalist wants to report the <em>typical</em> daily earnings. Which measure of center should she use, and why?',
    choices:[{key:'A',text:'Mean — it uses all data values'},{key:'B',text:'Mode — it is the most common value'},{key:'C',text:'Median — it is resistant to the outlier and better represents the center'},{key:'D',text:'Range — it shows the spread of earnings'}], answer:'C',
    explain:'The median is resistant to extreme outliers. The mean is pulled up by ₱960, making it unrepresentative.' },
  { part:2, text:'Daily fish prices (₱/kg) at a Navotas palengke over 8 days:{{DATA:85,90,92,88,90,95,90,102}}What is the mode?',
    choices:[{key:'A',text:'₱88'},{key:'B',text:'₱90'},{key:'C',text:'₱91.50'},{key:'D',text:'₱92'}], answer:'B',
    explain:'₱90 appears 3 times — more than any other value — making it the mode.' },
  { part:2, text:'Monthly electricity bills (₱) of 6 households in a Cebu subdivision:{{DATA:1840,2150,2380,2610,2750,3020}}What is the median monthly bill?',
    choices:[{key:'A',text:'₱2,380'},{key:'B',text:'₱2,490'},{key:'C',text:'₱2,495'},{key:'D',text:'₱2,610'}], answer:'C',
    explain:'n=6 (even): average the 3rd & 4th values = (2,380+2,610)/2 = ₱2,495.' },
  { part:2, text:'A dataset of exam scores has a mean of 78 and a median of 62. What does this most likely indicate about the distribution?',
    choices:[{key:'A',text:'The data is symmetric'},{key:'B',text:'The data is skewed left (negatively skewed)'},{key:'C',text:'The data is skewed right (positively skewed), pulled up by high scores'},{key:'D',text:'There is no mode in the dataset'}], answer:'C',
    explain:'Mean > Median suggests a right (positive) skew: a few very high scores pull the mean upward.' },
  { part:2, text:'Ten BSCS students reported the number of hours they spent coding last week:{{DATA:4,6,7,8,8,10,10,12,14,21}}What is the mean number of hours?',
    choices:[{key:'A',text:'9.0 hours'},{key:'B',text:'9.5 hours'},{key:'C',text:'10.0 hours'},{key:'D',text:'10.5 hours'}], answer:'C',
    explain:'Sum = 4+6+7+8+8+10+10+12+14+21 = 100. Mean = 100 ÷ 10 = 10.0 hours.' },
  { part:2, text:'Using the same coding-hours data:{{DATA:4,6,7,8,8,10,10,12,14,21}}What is the median?',
    choices:[{key:'A',text:'8 hours'},{key:'B',text:'9 hours'},{key:'C',text:'10 hours'},{key:'D',text:'10.5 hours'}], answer:'B',
    explain:'n=10 (even): average the 5th and 6th values = (8+10)/2 = 9 hours.' },
  { part:2, text:'Which of the following datasets is <em>bimodal</em>?',
    choices:[{key:'A',text:'{3, 5, 7, 9, 11}'},{key:'B',text:'{2, 4, 4, 6, 8, 8, 10}'},{key:'C',text:'{1, 2, 2, 2, 5, 6, 7}'},{key:'D',text:'{10, 20, 30, 40, 50}'}], answer:'B',
    explain:'In {2,4,4,6,8,8,10} both 4 and 8 appear twice — exactly two modes, so the data is bimodal.' },
  { part:2, text:'Monthly salaries (₱) of 5 workers at a small Iloilo restaurant:{{DATA:12500,13200,13800,14100,88000}}A new hire asks for the "average salary." Which single value would <em>most mislead</em> the new hire about typical pay?',
    choices:[{key:'A',text:'Median (₱13,800)'},{key:'B',text:'Mode (no repeated value)'},{key:'C',text:'Mean (₱28,320 — inflated by the ₱88,000 outlier)'},{key:'D',text:'Range (₱75,500)'}], answer:'C',
    explain:'Mean = (12,500+13,200+13,800+14,100+88,000)/5 = ₱28,320 — inflated far above typical pay by the outlier.' },

  // ── PART 3: Variability & Five-Number Summary ──
  { part:3, text:'Waiting times (in minutes) at a Quezon City LTO office on 6 randomly observed visits:{{DATA:18,25,31,37,42,55}}What is the range of waiting times?',
    choices:[{key:'A',text:'34 minutes'},{key:'B',text:'37 minutes'},{key:'C',text:'42 minutes'},{key:'D',text:'55 minutes'}], answer:'B',
    explain:'Range = Max − Min = 55 − 18 = 37 minutes.' },
  { part:3, text:'Number of absent students per day in a Manila high school class over 5 school days:{{DATA:2,5,3,8,7}}The sample mean is 5. What is the <em>sample variance</em>?',
    choices:[{key:'A',text:'5.0'},{key:'B',text:'5.5'},{key:'C',text:'6.5'},{key:'D',text:'7.0'}], answer:'C',
    explain:'Deviations²: (2−5)²=9, (5−5)²=0, (3−5)²=4, (8−5)²=9, (7−5)²=4. Sum=26. Variance = 26/(5−1) = 6.5.' },
  { part:3, text:'Using the same absence data (mean=5, variance=6.5):{{DATA:2,5,3,8,7}}What is the sample standard deviation (rounded to 2 decimal places)?',
    choices:[{key:'A',text:'2.35'},{key:'B',text:'2.55'},{key:'C',text:'2.65'},{key:'D',text:'3.00'}], answer:'B',
    explain:'s = √6.5 ≈ 2.55.' },
  { part:3, text:'Quiz scores (out of 50) for a BSCS section:{{DATA:22,28,33,35,38,41,44,46,48,50}}What is Q₁ (first quartile)?',
    choices:[{key:'A',text:'28'},{key:'B',text:'33'},{key:'C',text:'30.5'},{key:'D',text:'35'}], answer:'C',
    explain:'Lower half: {22,28,33,35,38}. Median of lower half (split-half method) = average of 2nd & 3rd = (28+33)/2 = 30.5.' },
  { part:3, text:'Using the same quiz score data:{{DATA:22,28,33,35,38,41,44,46,48,50}}What is the Interquartile Range (IQR)?',
    choices:[{key:'A',text:'13.5'},{key:'B',text:'16.5'},{key:'C',text:'16'},{key:'D',text:'18'}], answer:'B',
    explain:'Q₁=30.5, Q₃=(46+48)/2=47. IQR = 47 − 30.5 = 16.5.' },
  { part:3, text:'Two call centers measure call-handling time (in minutes). Center A has s=1.2 min; Center B has s=4.8 min. What does this tell us?',
    choices:[{key:'A',text:'Center A\'s agents handle calls faster on average'},{key:'B',text:'Center B\'s agents handle calls faster on average'},{key:'C',text:'Center A\'s call times are more consistent (less variable)'},{key:'D',text:'Center B\'s agents have a higher mean call time'}], answer:'C',
    explain:'A smaller standard deviation means less spread — Center A\'s agents are more consistent.' },
  { part:3, text:'Daily temperatures (°C) recorded in Baguio City over 7 days:{{DATA:14,15,16,17,17,18,22}}Which five-number summary is correct?',
    choices:[{key:'A',text:'Min=14, Q₁=15, Median=17, Q₃=18, Max=22'},{key:'B',text:'Min=14, Q₁=15.5, Median=17, Q₃=18, Max=22'},{key:'C',text:'Min=14, Q₁=15, Median=17, Q₃=17.5, Max=22'},{key:'D',text:'Min=14, Q₁=16, Median=17, Q₃=18, Max=22'}], answer:'A',
    explain:'Sorted: 14,15,16,17,17,18,22. Median=17 (4th value). Lower half: 14,15,16 → Q₁=15. Upper half: 17,18,22 → Q₃=18.' },
  { part:3, text:'A data value is a <em>potential outlier</em> if it falls below Q₁ − 1.5×IQR or above Q₃ + 1.5×IQR. For a dataset where Q₁=30 and Q₃=50, what is the <em>upper fence</em>?',
    choices:[{key:'A',text:'65'},{key:'B',text:'70'},{key:'C',text:'80'},{key:'D',text:'90'}], answer:'C',
    explain:'IQR = 50−30 = 20. Upper fence = Q₃ + 1.5×IQR = 50 + 30 = 80.' },
  { part:3, text:'Which formula correctly computes the <em>sample variance</em>?',
    choices:[{key:'A',text:'s² = Σ(x − x̄)² / n'},{key:'B',text:'s² = Σ(x − x̄)² / (n − 1)'},{key:'C',text:'s² = Σ(x − x̄) / (n − 1)'},{key:'D',text:'s² = √[Σ(x − x̄)² / n]'}], answer:'B',
    explain:'Sample variance uses (n−1) in the denominator (Bessel\'s correction): s² = Σ(x−x̄)² / (n−1).' },
  { part:3, text:'If a dataset has a standard deviation very close to 0, this means:',
    choices:[{key:'A',text:'The data values are spread far from the mean'},{key:'B',text:'The mean is close to zero'},{key:'C',text:'The data values are clustered closely around the mean'},{key:'D',text:'The dataset has many outliers'}], answer:'C',
    explain:'A standard deviation near 0 means all values are very close to the mean — very low variability.' },

  // ── PART 4: Probability & Events ──
  { part:4, text:'A box contains 5 red, 8 blue, and 7 white raffle tickets. One ticket is drawn at random. What is the probability of drawing a <em>blue</em> ticket?',
    choices:[{key:'A',text:'2/5'},{key:'B',text:'4/10'},{key:'C',text:'8/20'},{key:'D',text:'7/20'}], answer:'C',
    explain:'Total = 5+8+7 = 20. P(blue) = 8/20 = 0.40.' },
  { part:4, text:'In a group of 40 BSCS freshmen: 24 enrolled in Programming, 18 enrolled in Math, and 10 enrolled in both. Using the General Addition Rule, what is P(Programming OR Math)?',
    choices:[{key:'A',text:'0.70'},{key:'B',text:'0.80'},{key:'C',text:'0.85'},{key:'D',text:'1.05'}], answer:'B',
    explain:'P(P or M) = (24+18−10)/40 = 32/40 = 0.80.' },
  { part:4, text:'A fair coin is flipped three times. What is the probability of getting <em>exactly three heads</em>?',
    choices:[{key:'A',text:'1/2'},{key:'B',text:'1/4'},{key:'C',text:'1/8'},{key:'D',text:'3/8'}], answer:'C',
    explain:'Sample space has 2³=8 equally likely outcomes. Only HHH qualifies. P = 1/8.' },
  { part:4, text:'A bag has 6 green and 4 orange balls. Two balls are drawn <em>without replacement</em>. What is P(both green)?',
    choices:[{key:'A',text:'36/100'},{key:'B',text:'1/3'},{key:'C',text:'6/15'},{key:'D',text:'1/2'}], answer:'B',
    explain:'P(1st green)=6/10. P(2nd green | 1st green)=5/9. P(both)=30/90=1/3.' },
  { part:4, text:'A cybersecurity system: P(Flagged | Malicious)=0.95, P(Flagged | Safe)=0.04, P(Malicious)=0.02. Using the Law of Total Probability, what is P(Flagged)?',
    choices:[{key:'A',text:'0.0582'},{key:'B',text:'0.0574'},{key:'C',text:'0.0784'},{key:'D',text:'0.0812'}], answer:'A',
    explain:'P(Flagged) = 0.95×0.02 + 0.04×0.98 = 0.019 + 0.0392 = 0.0582.' },
  { part:4, text:'Events A and B are <em>mutually exclusive</em>. P(A)=0.30, P(B)=0.45. What is P(A or B)?',
    choices:[{key:'A',text:'0.135'},{key:'B',text:'0.65'},{key:'C',text:'0.75'},{key:'D',text:'1.00'}], answer:'C',
    explain:'Mutually exclusive → P(A or B) = P(A)+P(B) = 0.30+0.45 = 0.75.' },
  { part:4, text:'Which of the following scenarios involves <em>independent</em> events?',
    choices:[{key:'A',text:'Drawing two cards from a deck without replacement'},{key:'B',text:'Selecting two students to speak, where no one speaks twice'},{key:'C',text:'Rolling a die and flipping a coin simultaneously'},{key:'D',text:'Choosing a PIN where no digit repeats'}], answer:'C',
    explain:'A die roll and a coin flip do not affect each other — they are independent events.' },
  { part:4, text:'P(A)=0.5 and P(B)=0.4. If A and B are <em>independent</em>, what is P(A and B)?',
    choices:[{key:'A',text:'0.90'},{key:'B',text:'0.10'},{key:'C',text:'0.20'},{key:'D',text:'0.45'}], answer:'C',
    explain:'P(A and B) = P(A)×P(B) = 0.5×0.4 = 0.20.' },
  { part:4, text:'An email spam filter: P(Spam)=0.20, P("FREE"|Spam)=0.75, P("FREE"|Not Spam)=0.05. Using Bayes\' Theorem, what is P(Spam | "FREE")?',
    choices:[{key:'A',text:'0.75'},{key:'B',text:'0.79'},{key:'C',text:'0.81'},{key:'D',text:'0.85'}], answer:'B',
    explain:'P("FREE") = 0.75×0.20 + 0.05×0.80 = 0.15+0.04 = 0.19. P(Spam|"FREE") = 0.15/0.19 ≈ 0.79.' },
  { part:4, text:'The probability that a randomly chosen student passes the STAT 120 midterm is 0.73. What is the probability that the student does <em>not</em> pass?',
    choices:[{key:'A',text:'0.73'},{key:'B',text:'0.37'},{key:'C',text:'0.27'},{key:'D',text:'0.50'}], answer:'C',
    explain:'P(not pass) = 1 − P(pass) = 1 − 0.73 = 0.27.' },

  // ── PART 5: Counting Techniques ──
  { part:5, text:'What is the value of 7!?',
    choices:[{key:'A',text:'720'},{key:'B',text:'2,520'},{key:'C',text:'5,040'},{key:'D',text:'40,320'}], answer:'C',
    explain:'7! = 7×6×5×4×3×2×1 = 5,040.' },
  { part:5, text:'A school selects a <em>President, Vice President, and Secretary</em> from 12 student-council candidates. No candidate may hold two positions. How many arrangements are possible?',
    choices:[{key:'A',text:'220'},{key:'B',text:'1,320'},{key:'C',text:'1,728'},{key:'D',text:'479,001,600'}], answer:'B',
    explain:'Order matters (different positions). ₁₂P₃ = 12×11×10 = 1,320.' },
  { part:5, text:'A DepEd committee must choose 4 schools from 9 public schools to pilot a new curriculum. The order of selection does <em>not</em> matter. How many ways can this be done?',
    choices:[{key:'A',text:'126'},{key:'B',text:'3,024'},{key:'C',text:'6,561'},{key:'D',text:'362,880'}], answer:'A',
    explain:'Order does not matter. ₉C₄ = 9!/(4!×5!) = 126.' },
  { part:5, text:'A researcher wants to test all possible 4-feature subsets from 11 input features for a machine learning model. How many subsets must be tested?',
    choices:[{key:'A',text:'44'},{key:'B',text:'330'},{key:'C',text:'7,920'},{key:'D',text:'14,641'}], answer:'B',
    explain:'₁₁C₄ = 11!/(4!×7!) = 330.' },
  { part:5, text:'A system generates a 5-character password using only uppercase letters (A–Z), with <em>no repeated letters</em>. How many unique passwords are possible?',
    choices:[{key:'A',text:'65,780'},{key:'B',text:'7,893,600'},{key:'C',text:'11,881,376'},{key:'D',text:'26,000,000'}], answer:'B',
    explain:'Order matters, no repeats. ₂₆P₅ = 26×25×24×23×22 = 7,893,600.' },
  { part:5, text:'Which of the following problems requires a <em>combination</em> rather than a permutation?',
    choices:[{key:'A',text:'Arranging 6 trophies in a display case where order matters'},{key:'B',text:'Creating a 4-digit ATM PIN from digits 0–9 with no repeat'},{key:'C',text:'Selecting 5 peer-reviewers from 20 faculty members for a thesis panel'},{key:'D',text:'Ranking the top 3 teams in a programming competition'}], answer:'C',
    explain:'Choosing reviewers for a panel — the group matters, not their order — is a combination.' },
  { part:5, text:'From a pool of 7 women and 5 men, a research team of <em>2 women and 2 men</em> must be formed. How many different teams are possible?',
    choices:[{key:'A',text:'120'},{key:'B',text:'210'},{key:'C',text:'252'},{key:'D',text:'840'}], answer:'B',
    explain:'7C2 × 5C2 = 21 × 10 = 210.' },
  { part:5, text:'A BSCS professor selects 3 students from a class of 25 to present their projects. The order of presentation matters (1st, 2nd, 3rd). How many arrangements are there?',
    choices:[{key:'A',text:'2,300'},{key:'B',text:'12,650'},{key:'C',text:'13,800'},{key:'D',text:'15,600'}], answer:'C',
    explain:'Order matters. ₂₅P₃ = 25×24×23 = 13,800.' },
  { part:5, text:'Using the symmetry property nCr = nC(n−r), what is the value of ₁₅C₁₂?',
    choices:[{key:'A',text:'455'},{key:'B',text:'210'},{key:'C',text:'560'},{key:'D',text:'1,365'}], answer:'A',
    explain:'₁₅C₁₂ = ₁₅C₃ = (15×14×13)/(3×2×1) = 2730/6 = 455.' },
  { part:5, text:'How many unique 5-card hands can be dealt from a standard 52-card deck? (Order does not matter.)',
    choices:[{key:'A',text:'311,875,200'},{key:'B',text:'2,598,960'},{key:'C',text:'259,896'},{key:'D',text:'380,204,032'}], answer:'B',
    explain:'₅₂C₅ = 52!/(5!×47!) = 2,598,960.' },
];

async function seed() {
  console.log('Creating exam...');
  const examRes = await fetch(API + '/exams', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title: 'STAT 120 — Midterm Examination', description: '50 items · Multiple Choice · 60 minutes', time_limit: 60, questions_per_set: 10 }),
  });
  const { id: examId } = await examRes.json();
  console.log('Exam ID:', examId);

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    await fetch(API + '/exams/' + examId + '/questions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...q, sort_order: i }),
    });
    console.log(`  Added question ${i + 1}/${questions.length}`);
  }

  console.log('\nDone! Exam ID: ' + examId);
  console.log('Open: http://localhost:5173/exam?id=' + examId);
}

seed().catch(console.error);
